from custom_practice.runner import Case


TEST_CASES = [
    Case(
        name="empty store and no active transaction",
        args=((
            ("get", "missing"),
            ("commit",),
            ("rollback",),
        ),),
        expected=(None, False, False),
    ),
    Case(
        name="direct writes overwrite delete and zero value",
        args=((
            ("put", "a", 1),
            ("get", "a"),
            ("put", "a", 2),
            ("get", "a"),
            ("delete", "a"),
            ("get", "a"),
            ("put", "a", 0),
            ("get", "a"),
        ),),
        expected=(1, 2, None, 0),
    ),
    Case(
        name="rollback restores overwritten and newly created keys",
        args=((
            ("put", "a", 1),
            ("begin",),
            ("put", "a", 2),
            ("put", "b", 3),
            ("get", "a"),
            ("delete", "a"),
            ("get", "a"),
            ("rollback",),
            ("get", "a"),
            ("get", "b"),
        ),),
        expected=(2, None, True, 1, None),
    ),
    Case(
        name="nested child rollback restores parent view",
        args=((
            ("put", "k", 0),
            ("begin",),
            ("put", "k", 1),
            ("begin",),
            ("put", "k", 2),
            ("put", "child", 9),
            ("get", "k"),
            ("rollback",),
            ("get", "k"),
            ("get", "child"),
            ("commit",),
            ("get", "k"),
        ),),
        expected=(2, True, 1, None, True, 1),
    ),
    Case(
        name="inner commit remains reversible by outer rollback",
        args=((
            ("put", "a", 1),
            ("begin",),
            ("put", "a", 2),
            ("begin",),
            ("put", "a", 3),
            ("put", "b", 4),
            ("commit",),
            ("get", "a"),
            ("get", "b"),
            ("rollback",),
            ("get", "a"),
            ("get", "b"),
        ),),
        expected=(True, 3, 4, True, 1, None),
    ),
    Case(
        name="nested commits persist only after outer commit",
        args=((
            ("begin",),
            ("put", "a", 1),
            ("begin",),
            ("put", "a", 2),
            ("delete", "missing"),
            ("commit",),
            ("get", "a"),
            ("commit",),
            ("get", "a"),
            ("rollback",),
        ),),
        expected=(True, 2, True, 2, False),
    ),
    Case(
        name="nested rollback restores an outer deletion",
        args=((
            ("put", "x", 7),
            ("begin",),
            ("delete", "x"),
            ("get", "x"),
            ("begin",),
            ("put", "x", 9),
            ("get", "x"),
            ("rollback",),
            ("get", "x"),
            ("rollback",),
            ("get", "x"),
        ),),
        expected=(None, 9, True, None, True, 7),
    ),
    Case(
        name="committed child deletions merge through parent",
        args=((
            ("put", "a", 1),
            ("begin",),
            ("put", "b", 2),
            ("begin",),
            ("delete", "a"),
            ("delete", "b"),
            ("commit",),
            ("get", "a"),
            ("get", "b"),
            ("commit",),
            ("get", "a"),
            ("get", "b"),
        ),),
        expected=(True, None, None, True, None, None),
    ),
    Case(
        name="put after delete and delete after put",
        args=((
            ("put", "a", 1),
            ("begin",),
            ("delete", "a"),
            ("put", "a", 5),
            ("get", "a"),
            ("rollback",),
            ("get", "a"),
            ("begin",),
            ("put", "a", 6),
            ("delete", "a"),
            ("get", "a"),
            ("commit",),
            ("get", "a"),
        ),),
        expected=(5, True, 1, None, True, None),
    ),
    Case(
        name="three transaction levels unwind independently",
        args=((
            ("put", "value", 0),
            ("begin",),
            ("put", "value", 1),
            ("begin",),
            ("put", "other", 2),
            ("begin",),
            ("put", "value", 3),
            ("commit",),
            ("get", "value"),
            ("rollback",),
            ("get", "value"),
            ("get", "other"),
            ("commit",),
            ("get", "value"),
        ),),
        expected=(True, 3, True, 1, None, True, 1),
    ),
]
