from custom_practice.runner import Case


TEST_CASES = [
    Case(
        name="same timestamp respects the shortest rule",
        args=(
            ((3, 1), (20, 10)),
            (
                ("search", 1),
                ("search", 1),
                ("search", 1),
                ("search", 1),
            ),
        ),
        expected=(True, True, True, False),
    ),
    Case(
        name="exact cutoff expires the left boundary",
        args=(
            ((2, 5),),
            (
                ("api", 10),
                ("api", 11),
                ("api", 14),
                ("api", 15),
                ("api", 16),
            ),
        ),
        expected=(True, True, False, True, True),
    ),
    Case(
        name="rejected requests do not consume future quota",
        args=(
            ((1, 10),),
            (
                ("report", 1),
                ("report", 2),
                ("report", 3),
                ("report", 11),
            ),
        ),
        expected=(True, False, False, True),
    ),
    Case(
        name="different keys have independent limits",
        args=(
            ((2, 5),),
            (
                ("alpha", 7),
                ("alpha", 7),
                ("alpha", 7),
                ("beta", 7),
                ("beta", 7),
                ("beta", 7),
            ),
        ),
        expected=(True, True, False, True, True, False),
    ),
    Case(
        name="long rule rejects while short rule has capacity",
        args=(
            ((3, 1), (5, 10)),
            (
                ("warehouse", 1),
                ("warehouse", 1),
                ("warehouse", 2),
                ("warehouse", 2),
                ("warehouse", 3),
                ("warehouse", 3),
            ),
        ),
        expected=(True, True, True, True, True, False),
    ),
    Case(
        name="reported three per second and twenty per ten seconds",
        args=(
            ((3, 1), (20, 10)),
            (
                ("query", 1),
                ("query", 1),
                ("query", 1),
                ("query", 2),
                ("query", 2),
                ("query", 2),
                ("query", 3),
                ("query", 3),
                ("query", 3),
                ("query", 4),
                ("query", 4),
                ("query", 4),
                ("query", 5),
                ("query", 5),
                ("query", 5),
                ("query", 6),
                ("query", 6),
                ("query", 6),
                ("query", 7),
                ("query", 7),
                ("query", 7),
                ("query", 11),
                ("query", 11),
                ("query", 11),
                ("query", 11),
            ),
        ),
        expected=(
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            False,
            True,
            True,
            True,
            False,
        ),
    ),
    Case(
        name="all stale state is irrelevant after a long idle period",
        args=(
            ((2, 3), (4, 8)),
            (
                ("load", 1),
                ("load", 2),
                ("load", 3),
                ("load", 100),
                ("load", 100),
                ("load", 100),
            ),
        ),
        expected=(True, True, False, True, True, False),
    ),
    Case(
        name="rule order does not change the result",
        args=(
            ((4, 10), (2, 2)),
            (
                ("task", 1),
                ("task", 2),
                ("task", 3),
                ("task", 4),
                ("task", 5),
                ("task", 11),
            ),
        ),
        expected=(True, True, True, True, False, True),
    ),
]
