from custom_practice.runner import Case


TEST_CASES = [
    Case(
        name="empty executor returns None and cancels nothing",
        args=((
            ("execute",),
            ("cancel", "ghost"),
            ("execute",),
        ),),
        expected=(None, False, None),
    ),
    Case(
        name="a larger priority number executes first",
        args=((
            ("add", "a", 1, 0),
            ("add", "b", 5, 1),
            ("add", "c", 3, 2),
            ("execute",),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("b", "c", "a", None),
    ),
    Case(
        name="equal priority breaks by the earlier timestamp",
        args=((
            ("add", "late", 5, 30),
            ("add", "early", 5, 10),
            ("add", "middle", 5, 20),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("early", "middle", "late"),
    ),
    Case(
        name="equal priority and timestamp break by task id",
        args=((
            ("add", "banana", 2, 7),
            ("add", "apple", 2, 7),
            ("add", "cherry", 2, 7),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("apple", "banana", "cherry"),
    ),
    Case(
        name="re-adding an id raises the priority of the pending task",
        args=((
            ("add", "build", 1, 10),
            ("add", "test", 5, 20),
            ("add", "build", 9, 30),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("build", "test", None),
    ),
    Case(
        name="re-adding lowers priority and the stale entry must not win",
        args=((
            ("add", "build", 5, 10),
            ("add", "test", 3, 20),
            ("add", "build", 1, 30),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("test", "build", None),
    ),
    Case(
        name="repeated adds keep exactly one pending entry per id",
        args=((
            ("add", "job", 4, 1),
            ("add", "job", 4, 2),
            ("add", "job", 4, 3),
            ("execute",),
            ("execute",),
        ),),
        expected=("job", None),
    ),
    Case(
        name="cancel removes a pending task and reports whether it was pending",
        args=((
            ("add", "a", 5, 1),
            ("add", "b", 3, 2),
            ("cancel", "a"),
            ("cancel", "a"),
            ("cancel", "zzz"),
            ("execute",),
            ("execute",),
        ),),
        expected=(True, False, False, "b", None),
    ),
    Case(
        name="cancel after execute reports false",
        args=((
            ("add", "a", 5, 1),
            ("execute",),
            ("cancel", "a"),
            ("execute",),
        ),),
        expected=("a", False, None),
    ),
    Case(
        name="cancel then re-add makes the task pending again at its new priority",
        args=((
            ("add", "a", 5, 1),
            ("cancel", "a"),
            ("add", "a", 2, 9),
            ("add", "b", 3, 4),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=(True, "b", "a", None),
    ),
    Case(
        name="an executed id can be added again as a fresh task",
        args=((
            ("add", "a", 5, 1),
            ("execute",),
            ("add", "a", 1, 50),
            ("add", "b", 2, 60),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("a", "b", "a", None),
    ),
    Case(
        name="stale entries drain without changing the result",
        args=((
            ("add", "t", 1, 1),
            ("add", "t", 9, 2),
            ("add", "t", 4, 3),
            ("add", "u", 5, 4),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("u", "t", None),
    ),
    Case(
        name="out of order timestamps still order equal priorities",
        args=((
            ("add", "a", 5, 100),
            ("add", "b", 5, 50),
            ("add", "c", 5, 50),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("b", "c", "a"),
    ),
    Case(
        name="interleaved adds and executes",
        args=((
            ("add", "a", 1, 1),
            ("execute",),
            ("add", "b", 2, 2),
            ("add", "c", 3, 3),
            ("execute",),
            ("add", "d", 10, 4),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("a", "c", "d", "b", None),
    ),
    Case(
        name="negative priorities order the same way",
        args=((
            ("add", "a", -5, 1),
            ("add", "b", -1, 2),
            ("add", "c", 0, 3),
            ("execute",),
            ("execute",),
            ("execute",),
        ),),
        expected=("c", "b", "a"),
    ),
]
